[project]
name = "mcp-servers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp-server-time>=0.6.2",
    "mcp[cli]>=1.9.4",
    "psutil>=7.0.0",
]
